### PR TITLE
torch 2 support

### PR DESCRIPTION
**Pull request by lizelive**
https://github.com/hwchase17/langchain/pull/2865

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lizelive** [comment]
@conda-forge-admin, please rerender

**Comment by lizelive** [comment]
@YYYasin19 why didn't the bot update the dep?

**Comment by YYYasin19** [comment]
> @YYYasin19 why didn't the bot update the dep?

Not sure that's needed here, since we just change the dep version and nothing inherently important for the CI (e.g. other platforms)

**Comment by YYYasin19** [comment]
Looks good to me!

**Pull request merged**
