### PR TITLE
Fix tiktoken pinning

### PR DESCRIPTION
**Pull request by tarrade**
Checklist
*  [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix issue with upper limit for tiktoken >=0.3.2,<0.5.0 instead of 0.4.0

### CODE REVIEW

**Review by pavelzw — CHANGES_REQUESTED** [review]
https://github.com/langchain-ai/langchain/blob/v0.0.288/libs/langchain/pyproject.toml#L34
Upstream, the dependency is `^0.3.2`, i.e., `>=0.3.2,<0.4.0`. How about you change it upstream? Otherwise `pip check` will fail.

**Comment by tarrade** [comment]
@conda-forge-admin, please rerender

**Comment by tarrade** [comment]
@pavelzw I am not an expert but what I saw is that ^0.3.2 means any version greater that 0.3.2. I like the way conda-forge is doing by putting an upper. The latest version is 0.5.0 so the limit should be 0.6.0. Did I misundertood something ?

My issue is that with pip I can install the latest version of langchain with the latest version of tiktoken but not with conda-forge

**Comment by pavelzw** [comment]
https://python-poetry.org/docs/dependency-specification/#caret-requirements

image

These version constraints are automatically transferred from the `pyproject.toml` of the langchain project.
Being able to install langchain with tiktoken 0.5.0 seems like an issue with pip. The correct behavior should be that it's not installable together.

If you find that tiktoken 0.5.0 works well with langchain, please open a PR in the langchain repo similar to  https://github.com/langchain-ai/langchain/pull/2865 for example. As soon as this PR would be merged and released, the dependency specification of this repo will be updated.

**Comment by tarrade** [comment]
Thanks for the explanation. I will check again and follow your recommendation

**Comment by tarrade** [comment]
I created 2 conda env with the following: ` conda create --name test_conda python=3.9 pip` then in each identical env I installed tagged version of langchain and tiktoken with pip and conda

With pip it is working fine:
```
 pip install langchain==0.0.288 tiktoken==0.5.0
 Installing collected packages: urllib3, typing-extensions, tenacity, regex, PyYAML, packaging, numpy, mypy-extensions, multidict, idna, greenlet, frozenlist, charset-normalizer, certifi, attrs, async-timeout, annotated-types, yarl, typing-inspect, SQLAlchemy, requests, pydantic-core, numexpr, marshmallow, aiosignal, tiktoken, pydantic, dataclasses-json, aiohttp, langsmith, langchain
Successfully installed PyYAML-6.0.1 SQLAlchemy-2.0.20 aiohttp-3.8.5 aiosignal-1.3.1 annotated-types-0.5.0 async-timeout-4.0.3 attrs-23.1.0 certifi-2023.7.22 charset-normalizer-3.2.0 dataclasses-json-0.5.14 frozenlist-1.4.0 greenlet-2.0.2 idna-3.4 langchain-0.0.288 langsmith-0.0.37 marshmallow-3.20.1 multidict-6.0.4 mypy-extensions-1.0.0 numexpr-2.8.6 numpy-1.25.2 packaging-23.1 pydantic-2.3.0 pydantic-core-2.6.3 regex-2023.8.8 requests-2.31.0 tenacity-8.2.3 tiktoken-0.5.0 typing-extensions-4.7.1 typing-inspect-0.9.0 urllib3-2.0.4 yarl-1.9.
```

For conda, it is failing because of incompatibility:
```
conda install langchain=0.0.288 tiktoken=0.5.0
UnsatisfiableError: The following specifications were found to be incompatible with each other:
```

If I don't specify the version if tiktoken, the following is working:
`conda install langchain=0.0.288 tiktoken`

and the following version of tiktoken is installed:
`tiktoken                  0.3.3            py39h690f698_0    conda-forge`

This is consistent with the specification for conda-forge.

I don't know poetry but it seems that the package that are optional are not checked (I didn't find some proper explanation but here what I can see:

```
 pip show langchain     
Name: langchain
Version: 0.0.288
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /home/jupyter/.conda-env/test_pip/lib/python3.9/site-packages
Requires: aiohttp, async-timeout, dataclasses-json, langsmith, numexpr, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
```
and these packages are the one that are required:
```
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
pydantic = ">=1,<3"
SQLAlchemy = ">=1.4,<3"
requests = "^2"
PyYAML = ">=5.3"
numpy = "^1"
tenacity = "^8.1.0"
aiohttp = "^3.8.3"
numexpr = "^2.8.4"
langsmith = "~0.0.21"
dataclasses-json = "^0.5.7"
sync-timeout = {version = "^4.0.0", python = "<3.11"}
```

and the one with  `{version = "...", optional = true} seems to be ignore`

I don't know poetry but it is clear that the package build for pypi and conda-forge don't use the same information. The package on pypi ignore the package that are marked as "optional" while the package on conda-forge enforce them.

I am seeing that Rich is using the same strategy to include option package https://github.com/conda-forge/rich-feedstock/blob/main/recipe/meta.yaml

It seems that the "optional" are using in group when using poetry only. Did conda-forge decided to go and included all dependencies ?

I will test again the latest version of langchain and tiktoken and if it still work, I will do a PR as you suggested.

I am very confuse and don't really why poetry is interpret in different way

**Comment by tarrade** [comment]
@pavelzw you said that you have a tool that automatically convert the pyproject.toml dependency part for conda-forge package ?
I did something quick and dirty by comparing package version in langchain and conda-feedstock and I am still seeing some differences:
image
I don't see any conda package cassio and the one for marqo is incorrect for example

**Comment by pavelzw** [comment]
Hm yeah, that's a bit odd...
The last time it (or at least a part of it) worked was in #70.
The relevant line for this "tool" is this one. https://github.com/conda-forge/langchain-feedstock/blob/a4afbcbded1da9760322848684ace135a4aa8d73/conda-forge.yml#L8

It uses [grayskull](https://github.com/conda/grayskull) under the hood.
Maybe this is a bug in grayskull?

**Comment by pavelzw** [comment]
```bash
$ grayskull pypi langchain
$ cat langchain/meta.yaml | grep marqo
    - marqo >=1.2.4,<2.0.0
```

So grayskull seems to work but for some reason the `bot.inspection: update-grayskull` is not doing what it's supposed to...

**Comment by pavelzw** [comment]
> I don't see any conda package cassio

This is because nobody cared yet to port it to conda-forge. Since this is only an optional dependency, this doesn't break this build here.

**Comment by tarrade** [comment]
PR is here https://github.com/langchain-ai/langchain/pull/10640, if/when approved, I will update this PR

**Comment by tarrade** [comment]
Hi @pavelzw ,

The modification for tiktoken was introduced in langcain v0.0.305 https://github.com/langchain-ai/langchain/releases/tag/v0.0.305

Now, I checked langchain-feedstock for v0.0.306 and I don't see the modification being propagated properly:
tiktoken >=0.3.2,<0.4.0
https://github.com/conda-forge/langchain-feedstock/blob/main/recipe/meta.yaml

I am happy to do a PR to fix  it manually but since you told me it should be done automatically by getting the info directly from libs/langchain/pyproject.toml just wondering if something wrong happen in the last automatic PR

**Comment by pavelzw** [comment]
Thanks for keeping track of this @tarrade! Yeah, in a perfect world, this should have gotten updated automatically by the bot but for some reason, this is not the case...
Happy to merge a PR that fixes the tiktoken pinnings.

**Review by pavelzw — APPROVED** [review]

**Comment by pavelzw** [comment]
Thanks for the PR @tarrade. If you find other discrepancies between this feedstock and the pyproject.toml from upstream, feel free to create another PR here.

**Pull request merged**
